name: invoice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  pdf: ^3.10.8
  flutter_pdfview: ^1.3.2
  printing: ^5.12.0
  speech_to_text: ^6.6.0
  provider: ^6.1.1
  avatar_glow: ^3.0.1
  audioplayers: ^5.2.1
  csv: ^5.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.0.13
  advance_pdf_viewer2: ^2.0.5+1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/fonts/robotoregular.ttf
  

fonts:
    - family: robotoregular
      fonts:
        - asset: assets/fonts/robotoregular.ttf




